oauth-server: http://localhost:9120

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 20000
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    prefer-ip-address: true
    #    发送心跳时间间隔 默认30
    lease-renewal-interval-in-seconds: 10
    #    服务端收到最后一次心跳之后等待的时间上限 超过则剔除（客户端告诉服务端按照此规则）
    lease-expiration-duration-in-seconds: 22
