oauth-server: http://172.18.0.1:9120

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.18.0.1:3306/seckill?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: root
    password: '{cipher}AQAPa2DT2Lfbq6+Xe8tktDRFqlsnZTe9S0tctbCk1CI2VmgAI2hgfi/8+p7sFTJP40+C7ePYfGWiJDz0cvsQ5OmCR4yXKipfsx+KFba6/ndeObumluiAhlqPSAPl/ROeKpCvXSHKu7F6duvrYy+vNuz+SccZRzVWBaMm5nGntifwbDnhj0zbQZkhDxZzJgd7A/5bMN3k0OEtVFS/QzQwvqqFWVdmphPDV7MSQuC/ttRVcPSFsMjImN36pZgZboAZfeew19IXt9PLIe6lRf47h6l/wl57aeCY/Fe9Vh7luAyVm6ldxwBDlXQ6LqaMqHoPcnyzL1YhbEo3i7qtQpiu1ItZfXruaYkYsjNviG+F+yqhQ6q1Ax8aO3hVsHezhtl8Dcs='
  redis:
    host: 172.18.0.1
    port: 6379
    password: 123456
    timeout: 20000
    database: 0
  rabbitmq:
    host: 172.18.0.1
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    prefer-ip-address: true
    #    发送心跳时间间隔 默认30
    lease-renewal-interval-in-seconds: 10
    #    服务端收到最后一次心跳之后等待的时间上限 超过则剔除（客户端告诉服务端按照此规则）
    lease-expiration-duration-in-seconds: 22
