info:
  profile: dev
  from: git
  data: {cipher}AQAH6K8u5q7zv70cxbsXpma21YMEASIgo1jwnFOkPXnwFCiQ5nZYYbcPWxBC5Jyo6iocwDrhNXp5oQXno3St6uT9F6kv2uIUxeHzJo9E95l23CbEs2WpxWnb1onlRh2PAUQUKABpeDAMzZiI7XttWTxMtF7/qgHWQOkvgOL45hrFpUjIyF9ypRwcMQw7xsluIAIqMjUU1njVKFHcceDQmW4XR9f/Gd7N0rX+tUXHahBVWsXm5Xoz3zWa2ZbwI+FkL6dTRc2u8XZ+xYhv/HVQmL5+mdS6OmytO3y46qkWkvv1IRWLQhYSghxZY0xzhBmkY92UHWizFIvrBt1ofN8kF74x1NRoBPumIV1oeBMDRMLMhI1oUdw9VV6Ah2vajkeisV0=
