server:
  port: 8620
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: config-client

env: '{cipher}AQCC7CId6QWbctFvkRRc4Q91UJ2iAZLKma1nK0KghQMesUDFamF7JjYox7T5pWBicZZ0/5LBJwfqLe15hTVWvxRZUssbbd/Z8R28aynyE4Vk9asGmIDbpDs5MlNxN7dL7LDoH02JWKLf9Ts9/gK7FIrbkQgPNbEZoaeaHF4v8TPdaVHJvPCbJG7FG+dK3O4HLA6AQS9IbzHIyNrH+87zZL3ilNQyc1/zj7PjJuuhLi2tASNDghsjldE13212GQVnqCSZ9cJOLlUHDxK+QXvPdnE+4v0G0rqu3CHX02ILKUBbRwhJwl913TTs7VDoLz5AcmdOWV7fAvG4CGyPiSdRxIrNHyvSza4EfhyMiro/zGB2KGQWUlJpAlGgdPUImlHQmGM='